package com.allbill127.psk_lab1.mybatis.entities;

import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.ID
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.CAPITAL
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    private BigDecimal capital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.EMAIL
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.NAME
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    private String name;
}