package com.allbill127.psk_lab1.mybatis.entities;

import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;

@Getter
@Setter
public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.SALARY
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.COMPANY_ID
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.PERSON_ID
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    private Long personId;
}