package com.allbill127.psk_lab1.mybatis.dao;

import com.allbill127.psk_lab1.mybatis.entities.Owner;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface OwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    int insert(Owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    List<Owner> selectAll();
}