package com.allbill127.psk_lab1.mybatis.dao;

import com.allbill127.psk_lab1.mybatis.entities.Person;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    Person selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    List<Person> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Thu Apr 20 20:34:32 EEST 2023
     */
    int updateByPrimaryKey(Person record);
}